### PR TITLE
Upgrade vitest and eslint plugin versions

### PR DESCRIPTION
**Pull request by HannaTarasevich**

### CODE REVIEW

**Review by christian-bromann — COMMENTED** [review]
Awesome work 🎉 can you check the failing unit tests? I know these are likely unrelated to your changes but it would be great if we could also get these fixed.

**Comment by HannaTarasevich** [comment]
Hi @christian-bromann ,
Thanks and for sure, I'll fix this

**Comment by HannaTarasevich** [comment]
Hi @christian-bromann,
The PR is ready for your review. Please take a look when you have time.

Thank you!

**Review by christian-bromann — APPROVED** [review]
This is great work, thanks so much 🙏

**Pull request merged**
