### PR TITLE
core: update to latest deps

### PR DESCRIPTION
**Pull request by wswebcreation**

### CODE REVIEW

**Comment by wswebcreation** [comment]
@christian-bromann 

I'm trying to upgrade the package to support V8, but when I link it to a simple WDIO project with CucumberJS I get the following logs

In https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/issues/96 you mentioned that reporters don't need to be migrated yet to ESM, but not sure what the issue is now.
Secondly, I looked into some other modules that are migrated to ESM and tbh, I don't exactly know what I need to change to makes sure it works. Any tips/tricks for this?

Thanks!

```logs
yarn test.local --logLevel=debug                                      took  5s
yarn run v1.22.19
warning ../../../../../package.json: No license field
$ wdio test/configs/wdio.local.chrome.conf.js --logLevel=debug

Execution of 1 workers started at 2022-12-22T07:26:10.399Z

2022-12-22T07:26:10.414Z DEBUG @wdio/utils:initialiseServices: initialise service "chromedriver" as NPM package
2022-12-22T07:26:10.444Z INFO chromedriver: Initiate Chromedriver Launcher (v8.0.1)
2022-12-22T07:26:10.444Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-12-22T07:26:10.449Z INFO chromedriver: Start Chromedriver (/Users/wimselles/Sauce/Git/wdio-samples/wdio-cucumber-v6-v7-v8/v8/node_modules/chromedriver/lib/chromedriver/chromedriver) with args --port=9515 --url-base=/
2022-12-22T07:26:10.482Z INFO chromedriver: Starting ChromeDriver 108.0.5359.71 (1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}) on port 9515
2022-12-22T07:26:10.483Z INFO chromedriver: Only local connections are allowed.
2022-12-22T07:26:10.483Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2022-12-22T07:26:10.497Z INFO chromedriver: ChromeDriver was started successfully.
2022-12-22T07:26:10.567Z DEBUG @wdio/cli:utils: Finished to run "onPrepare" hook in 120ms
2022-12-22T07:26:10.570Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-12-22T07:26:10.570Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms
2022-12-22T07:26:10.571Z INFO @wdio/local-runner: Start worker 0-0 with arg: test/configs/wdio.local.chrome.conf.js,--logLevel=debug
2022-12-22T07:26:10.583Z DEBUG @wdio/local-runner: Send command run to worker with cid "0-0"
[0-0] 2022-12-22T07:26:11.520Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2022-12-22T07:26:11.549Z DEBUG @wdio/runner: init remote session
[0-0] 2022-12-22T07:26:11.556Z DEBUG @wdio/utils:initialiseServices: initialise service "chromedriver" as NPM package
[0-0] RUNNING in chrome - file:///test/features/sample.feature
[0-0] 2022-12-22T07:26:11.887Z DEBUG @wdio/runner: init remote session
[0-0] 2022-12-22T07:26:11.892Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2022-12-22T07:26:11.981Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2022-12-22T07:26:11.981Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       'goog:chromeOptions': [Object],
[0-0]       'cjson:metadata': [Object]
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     'goog:chromeOptions': { args: [Array] },
[0-0]     'cjson:metadata': { device: 'Test Device', browser: [Object], platform: [Object] }
[0-0]   }
[0-0] }
[0-0] 2022-12-22T07:26:13.073Z ERROR @wdio/runner: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/wimselles/Sauce/Git/wdio-services/wdio-cucumberjs-json-reporter/node_modules/@wdio/reporter/build/index.js
[0-0] require() of ES modules is not supported.
[0-0] require() of /Users/wimselles/Sauce/Git/wdio-services/wdio-cucumberjs-json-reporter/node_modules/@wdio/reporter/build/index.js from /Users/wimselles/Sauce/Git/wdio-services/wdio-cucumberjs-json-reporter/dist/reporter.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
[0-0] Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/wimselles/Sauce/Git/wdio-services/wdio-cucumberjs-json-reporter/node_modules/@wdio/reporter/package.json.
[0-0] 
[0-0]     at new NodeError (internal/errors.js:322:7)
[0-0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
[0-0]     at Module.load (internal/modules/cjs/loader.js:950:32)
[0-0]     at Module._load (internal/modules/cjs/loader.js:790:12)
[0-0]     at Function.hookedLoader [as _load] (/Users/wimselles/Sauce/Git/wdio-samples/wdio-cucumber-v6-v7-v8/v8/node_modules/mockery/mockery.js:111:12)
[0-0]     at Module.require (internal/modules/cjs/loader.js:974:19)
[0-0]     at require (internal/modules/cjs/helpers.js:101:18)
[0-0]     at Object.<anonymous> (/Users/wimselles/Sauce/Git/wdio-services/wdio-cucumberjs-json-reporter/lib/reporter.ts:24:1)
[0-0]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[0-0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[0-0]  Error:  Must use import to load ES Module: /Users/wimselles/Sauce/Git/wdio-services/wdio-cucumberjs-json-reporter/node_modules/@wdio/reporter/build/index.js
require() of ES modules is not supported.
require() of /Users/wimselles/Sauce/Git/wdio-services/wdio-cucumberjs-json-reporter/node_modules/@wdio/reporter/build/index.js from /Users/wimselles/Sauce/Git/wdio-services/wdio-cucumberjs-json-reporter/dist/reporter.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/wimselles/Sauce/Git/wdio-services/wdio-cucumberjs-json-reporter/node_modules/@wdio/reporter/package.json.

[0-0] 2022-12-22T07:26:13.074Z INFO webdriver: COMMAND deleteSession()
[0-0] 2022-12-22T07:26:13.075Z INFO webdriver: [DELETE] http://localhost:9515/session/606071b0e53f5110592690a668040512
2022-12-22T07:26:13.248Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - file:///test/features/sample.feature
2022-12-22T07:26:13.248Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-12-22T07:26:13.248Z DEBUG @wdio/cli:utils: Finished to run "onWorkerEnd" hook in 0ms
2022-12-22T07:26:13.249Z INFO @wdio/cli:launcher: Run onComplete hook
2022-12-22T07:26:13.250Z ERROR @wdio/cli:utils: Error in onCompleteHook: Error: There were issues reading JSON-files from '.tmp/json/'.
    at collectJSONS (/Users/wimselles/Sauce/Git/wdio-samples/wdio-cucumber-v6-v7-v8/v8/node_modules/multiple-cucumber-html-reporter/lib/collect-jsons.js:26:15)
    at generateReport (/Users/wimselles/Sauce/Git/wdio-samples/wdio-cucumber-v6-v7-v8/v8/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:78:23)
    at Object.onComplete (/Users/wimselles/Sauce/Git/wdio-samples/wdio-cucumber-v6-v7-v8/v8/test/configs/wdio.shared.conf.js:73:5)
    at file:///Users/wimselles/Sauce/Git/wdio-samples/wdio-cucumber-v6-v7-v8/v8/node_modules/@wdio/cli/build/utils.js:101:19
    at Array.map (<anonymous>)
    at runOnCompleteHook (file:///Users/wimselles/Sauce/Git/wdio-samples/wdio-cucumber-v6-v7-v8/v8/node_modules/@wdio/cli/build/utils.js:99:39)
    at Launcher.run (file:///Users/wimselles/Sauce/Git/wdio-samples/wdio-cucumber-v6-v7-v8/v8/node_modules/@wdio/cli/build/launcher.js:92:45)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-12-22T07:26:13.250Z DEBUG @wdio/cli:utils: Finished to run "onComplete" hook in 0ms

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:02 

2022-12-22T07:26:13.251Z INFO @wdio/local-runner: Shutting down spawned worker
2022-12-22T07:26:13.502Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-12-22T07:26:13.503Z INFO @wdio/local-runner: shutting down
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by christian-bromann** [comment]
Hey Wim,
your reporter should be able to be used in v8 projects which is what I meant when I said they don't need to migrate to ESM. However if you want to update to `v8` you will have to migrate this reporter to ESM as well. Is that what you wanted to do? Let me know if I can help with that.

**Comment by christian-bromann** [comment]
@wswebcreation anything I can do to help moving this forward. I believe the easiest way to ensure v8 support is to include the version as peer dep in [this line](https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/blob/main/package.json#L53). A migration to ESM is not really necessary, desire-able though 😉 .

**Comment by wswebcreation** [comment]
Hi @christian-bromann 

I'm totally swamped with everything, private and work atm, to be able to work on it.

This module also uses V7 dependencies, and if we upgrade to it we need to migrate to ESM, or am I wrong?

**Comment by rameshkumarj** [comment]
Any idea when the updated package for wdio8 be available

**Comment by christian-bromann** [comment]
> Any idea when the updated package for wdio8 be available

Please see comments above. Feel free to get involved to push this over the goal line. What's needed to do is to transform the code base to ESM (with CJS export included) and update all dependencies.

**Comment by mat-sharp** [comment]
Happy to get involved in helping on this if there is anything I can do?

**Comment by christian-bromann** [comment]
@mat-sharp feel free to raise a new PR with updated deps.

**Comment by christian-bromann** [comment]
@jelugbo I am still getting build errors after merging and rebase.

**Comment by bjelugbo** [comment]
Screenshot 2023-04-07 at 1 08 23 PM

I'm not sure why you are getting that error, I dispatched that workflow on my repo and didn't have those build errors. Can you take a look once again?

**Comment by christian-bromann** [comment]
@bjelugbo can you try checkout the project out in a fresh directory? You see the issues in our pipeline too: https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/actions/runs/4638908738/jobs/8209179144?pr=113

**Comment by bjelugbo** [comment]
@christian-bromann , created a PR to fix the type issues

**Comment by christian-bromann** [comment]
> created a PR to fix the type issues

Can you provide a link?

**Comment by christian-bromann** [comment]
I incorporated your changes and updated the code base. Will make a v5 release now. Thanks to everyone involved for pushing this forward. Please let me know if the reporter works.

**Pull request closed without merging**
