### PR TITLE
Fix wdio/cucumber-framework dependency

### PR DESCRIPTION
**Pull request by HannaTarasevich**
Fix https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/issues/582

### CODE REVIEW

**Review by christian-bromann — COMMENTED** [review]
I think we should update all peer dependencies of WebdriverIO to v9, right?

**Comment by HannaTarasevich** [comment]
I wish I could :)

There are breaking changes in v9, that say:
Capabilities.DesiredCapabilities
Capabilities.Capabilities
browser.options.capabilities
data.config.capabilities
WebDriver.DesiredCapabilities

are no longer accessible. So I'm not really sure what can be a good replacer for these cases

**Comment by christian-bromann** [comment]
> Capabilities.DesiredCapabilities
> Capabilities.Capabilities

The correct types for capabilities are `WebdriverIO.Capabilities` , don't import them anymore via `import { Capabilities } from '@wdio/types'`. We try to put all user facing types into the `WebdriverIO` namespace.

> browser.options.capabilities
> data.config.capabilities

If you want to access the capabilities sent to the driver, you can use `browser.requestedCapabilities`, if you like to access the capabilities that the driver responded with and uses for the session, use `browser.capabilities`.

> WebDriver.DesiredCapabilities

This should be replaced with `WebdriverIO.Capabilities`.

Let me know if there are more information I can provide. Thank you!

**Comment by HannaTarasevich** [comment]
Many thanks! I'll continue work on the PR

**Comment by db798** [comment]
Is there any update on if/when this will be available. I'm looking to update to WebdriverIO v9 and it would be great if I could continue to use this package.

**Comment by HannaTarasevich** [comment]
@db798 In case of any need feel to speed up the update, feel free to contribute and raise a separate PR.

**Comment by Sven-Seyfert** [comment]
Hi @HannaTarasevich 👋 ,

I don't wont to bother you, but I don't get your statement. You started to develop the (a) fix, commited this one and now the PR is closed? What has to be done to get the fix into the WDIO v9.0.x version? I would contribute, but I am unsure what has to be fixed more then your dependency update?

Missed I some conversation about it? I don't get it 😅 .
Thanks for your feedback.

Best regards
Sven

**Comment by HannaTarasevich** [comment]
Hi @Sven-Seyfert ,
Please read the thread in the PR. 
There is no updates from my side, so the PR is closed and you're very welcome to fix the issue.
Thanks.

**Pull request closed without merging**
