### PR TITLE
Addressed #79

### PR DESCRIPTION
**Pull request by bhaslamb**
* Updated wdio/ cucumber-framework peer dependency to resolve conflicts.

### CODE REVIEW

**Comment by wswebcreation** [comment]
Thanks for the PR @bhaslamb 

I'm only wondering if peerDependencies are the best usage here, same with pinpointing a version. 

@christian-bromann, I don't have enough knowledge about the peerdependencies, do you have that so we can make this more stable (or just remove it)?

**Comment by bhaslamb** [comment]
I think I can include #76 as part of this PR. what do you think?

**Comment by wswebcreation** [comment]
let's keep them separate.

**Comment by bhaslamb** [comment]
> @christian-bromann, I don't have enough knowledge about the peerdependencies, do you have that so we can make this more stable (or just remove it)?
@christian-bromann - You answer could be useful to get rid of peer dependency warnings during installation.

**Comment by wswebcreation** [comment]
Closing this one because it's fixed with #84

**Pull request closed without merging**
