### PR TITLE
Addressed #69 to introduce optional property to disable hooks information in json

### PR DESCRIPTION
**Pull request by bhaslamb**

### CODE REVIEW

**Comment by wswebcreation** [comment]
Thanks for the PR

can you also create unit tests for them?

**Comment by bhaslamb** [comment]
Not sure  whether my test is okay for you, please check and let me know.

**Comment by wswebcreation** [comment]
Tnx, looks good. Last thing, can you also update the docs 

I’ll do a last check tomorrow morning and when the docs are up to date and my last check it good I’ll merge it and release a new version 

Again, thanks!!

**Comment by bhaslamb** [comment]
Sorry to not added in last commit. its done.

**Comment by wswebcreation** [comment]
Thanks, merged it and will release it asap

**Pull request merged**
